# Orthogonal Fourier matrix

The following Jupyter notebook contains the definition and basic implementation of orthogonal Fourier matrix.

### Tunable parameters 
- L - the length of a periodic domain where a Fourier series is defined
- N - the number of waves
- (2*N + 1) - the number of grid points
- x - the symmetric discrete domain ranging from -L/2 to L/2

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
L = 20.0
N = 5
grid_points = 2*N+1

### Initialize the grid

In [3]:
x = np.zeros(grid_points)
for j in range(grid_points):
    x[j] = L * (j-N)/grid_points

In [4]:
x

array([-9.09090909, -7.27272727, -5.45454545, -3.63636364, -1.81818182,
        0.        ,  1.81818182,  3.63636364,  5.45454545,  7.27272727,
        9.09090909])

### Initialize the Fourier transform

In [5]:
F = np.zeros((grid_points, 2*N+1))

In [6]:
F

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Calculate the Fourier transform

In [7]:
for j in range(grid_points):
    for n in range(0,N+1):
        if n == 0:
            F[j, n] = 1/np.sqrt(2)
        else:
            F[j,2*n-1] = np.cos(2*np.pi*(2*n-1)*x[j]/L)
            F[j,2*n] = np.sin(2*np.pi*(2*n-1)*x[j]/L)
        #print j,n,F[j,n]
F = F * np.sqrt(2./grid_points)

### Transpose the Fourier transform

In [8]:
F_t = F.transpose()

### Consistency check: F * F_t = 1 (unitary matrix)

In [9]:
np.where(np.array(np.matmul(F, F_t)) > 0.5, 1, 0)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## Definitions of functions (to be used in the future)

In [10]:
def orthogonal_fourier(L, N):
    grid_points = 2*N + 1
    
    x = np.zeros(grid_points)
    for j in range(grid_points):
        x[j] = L * (j-N)/grid_points
        
    F = np.zeros((grid_points, 2*N+1))
    for j in range(grid_points):
        for n in range(0,N+1):
            if n == 0:
                F[j, n] = 1.0/np.sqrt(2.0)
            else:
                F[j,2*n-1] = np.cos(2.0*np.pi*(2*n-1)*x[j]/L)
                F[j,2*n] = np.sin(2.0*np.pi*(2*n-1)*x[j]/L)
    F = F * np.sqrt(2.0/grid_points)
    
    return F

In [11]:
def unitarity_test(F, N):
    F_t = np.transpose(F)
    
    array_to_test = np.where(np.array(np.matmul(F, F_t)) > 0.5, 1, 0)
    #print(array_to_test)
    if np.array_equal(array_to_test, np.identity(2*N + 1, dtype=np.int32)):
        return True
    else:
        return False
    

In [12]:
L = 10.0
N = 40
F = orthogonal_fourier(L, N)
print("Fourier transform")
print(F)
test = unitarity_test(F, N)
print("Unitarity: %s"%test)

Fourier transform
[[ 0.11111111 -0.15701667 -0.00609296 ... -0.02428029  0.15666233
  -0.01217676]
 [ 0.11111111 -0.15607235 -0.01824224 ... -0.07052199  0.15289925
  -0.03623779]
 [ 0.11111111 -0.1541894  -0.03028181 ... -0.11002854  0.14546349
  -0.05942837]
 ...
 [ 0.11111111 -0.1541894   0.03028181 ...  0.11002854  0.14546349
   0.05942837]
 [ 0.11111111 -0.15607235  0.01824224 ...  0.07052199  0.15289925
   0.03623779]
 [ 0.11111111 -0.15701667  0.00609296 ...  0.02428029  0.15666233
   0.01217676]]
Unitarity: True


In [13]:
L = 10.0
N = 120
F = orthogonal_fourier(L, N)
print("Fourier transform")
print(F)
test = unitarity_test(F, N)
print("Unitarity: %s"%test)

Fourier transform
[[ 0.06441566 -0.09108976 -0.00118748 ... -0.00474791  0.09106655
  -0.00237476]
 [ 0.06441566 -0.09102785 -0.00356164 ... -0.01419214  0.090819
  -0.00711783]
 [ 0.06441566 -0.09090407 -0.00593337 ... -0.02348217  0.0903246
  -0.01184155]
 ...
 [ 0.06441566 -0.09090407  0.00593337 ...  0.02348217  0.0903246
   0.01184155]
 [ 0.06441566 -0.09102785  0.00356164 ...  0.01419214  0.090819
   0.00711783]
 [ 0.06441566 -0.09108976  0.00118748 ...  0.00474791  0.09106655
   0.00237476]]
Unitarity: True
